### ISSUE TITLE
System.OverflowException: Value was either too large or too small for a UInt32.

### ISSUE THREAD

**Issue by danieljin** [andyjmorgan/CaffeineForCitrixWorkspace#6]
************** Exception Text **************
System.OverflowException: Value was either too large or too small for a UInt32.
   at System.Convert.ToUInt32(Int32 value)
   at Caffeine.lastinput.GetIdletime()
   at Caffeine.Tray_Main.tmrCheckSessions_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by danieljin** [comment]
@andyjmorgan I believe the issue is just an int32 that needs to be updated to int64

**Comment by danieljin** [comment]
nvm this is a caffeine for receiver error, not workspace
